name: iagno
adopt-info: iagno
# The appstream version has newline breaks which the snap store doesn't accept
# Store upload failed:
# __all__: summary: Multiple lines are not allowed.
summary: Dominate the board in a classic reversi game or play the reversed variant
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

slots:
  # for GtkApplication registration
  iagno:
    interface: dbus
    bus: session
    name: org.gnome.Reversi

layout:
 /usr/share/iagno:
   symlink: $SNAP/usr/share/iagno

apps:
  iagno:
    extensions: [ gnome ]
    common-id: org.gnome.Reversi.desktop
    command: usr/bin/iagno
    desktop: usr/share/applications/org.gnome.Reversi.desktop
    plugs:
      - audio-playback

parts:
  iagno:
    source: https://gitlab.gnome.org/GNOME/iagno.git
    source-type: git
    source-tag: '3.38.1'
    parse-info: [usr/share/metainfo/org.gnome.Reversi.appdata.xml]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/patches/patch1.diff
    override-build: |
      sed -i.bak -e 's|=org.gnome.Reversi$|=${SNAP}/meta/gui/iagno.svg|g' $CRAFT_PART_SRC/data/org.gnome.Reversi.desktop.in
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/icons/hicolor/scalable/org.gnome.Reversi.svg $CRAFT_PART_INSTALL/meta/gui/iagno.svg
      cp $CRAFT_PART_BUILD/data/org.gnome.Reversi.desktop $CRAFT_PART_INSTALL/meta/gui/
